[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_project = "9YVEZcFtNkqyNWUNqEchHdVVLBx3rtX7W1E2cuMrwdGd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/longjiuwei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
